<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="158282" started-at="2017-06-16T05:32:55Z" finished-at="2017-06-16T05:35:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="158282" started-at="2017-06-16T05:32:55Z" finished-at="2017-06-16T05:35:34Z">
      <class name="PajeObject.LoginCases">
        <test-method status="PASS" signature="setUp()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="setUp" is-config="true" duration-ms="5324" started-at="2017-06-16T11:17:55Z" finished-at="2017-06-16T11:18:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="blankLogin()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="blankLogin" duration-ms="23160" started-at="2017-06-16T11:18:01Z" finished-at="2017-06-16T11:18:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blankLogin -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="setUp" is-config="true" duration-ms="2862" started-at="2017-06-16T11:18:24Z" finished-at="2017-06-16T11:18:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="invalidPassword()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="invalidPassword" duration-ms="17180" started-at="2017-06-16T11:18:27Z" finished-at="2017-06-16T11:18:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error! Username / Password Incorrect] but found [ Error! Username / Password Incorrect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error! Username / Password Incorrect] but found [ Error! Username / Password Incorrect]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at PajeObject.LoginCases.invalidPassword(LoginCases.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidPassword -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="setUp" is-config="true" duration-ms="2631" started-at="2017-06-16T11:18:44Z" finished-at="2017-06-16T11:18:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="invalidUsername()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="invalidUsername" duration-ms="10797" started-at="2017-06-16T11:18:47Z" finished-at="2017-06-16T11:18:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error! Username / Password Incorrect] but found [ Error! Username / Password Incorrect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error! Username / Password Incorrect] but found [ Error! Username / Password Incorrect]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at PajeObject.LoginCases.invalidUsername(LoginCases.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUsername -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="setUp" is-config="true" duration-ms="3273" started-at="2017-06-16T11:18:57Z" finished-at="2017-06-16T11:19:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="invalidUsernameAndPassword()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="invalidUsernameAndPassword" duration-ms="25720" started-at="2017-06-16T11:19:01Z" finished-at="2017-06-16T11:19:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Error! Username / Password Incorrect] but found [ Error! Username / Password Incorrect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Error! Username / Password Incorrect] but found [ Error! Username / Password Incorrect]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at PajeObject.LoginCases.invalidUsernameAndPassword(LoginCases.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUsernameAndPassword -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="setUp" is-config="true" duration-ms="3111" started-at="2017-06-16T11:19:26Z" finished-at="2017-06-16T11:19:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validUsernameAndPassword()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="validUsernameAndPassword" duration-ms="42270" started-at="2017-06-16T11:19:30Z" finished-at="2017-06-16T11:20:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUsernameAndPassword -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:PajeObject.LoginCases@1593948d]" name="setUp" is-config="true" duration-ms="3447" started-at="2017-06-16T11:20:12Z" finished-at="2017-06-16T11:20:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validUsernameAndPasswordUsingDataProvider(java.lang.String, java.lang.String)[pri:0, instance:PajeObject.LoginCases@1593948d]" name="validUsernameAndPasswordUsingDataProvider" duration-ms="18334" started-at="2017-06-16T11:20:15Z" data-provider="Authentication" finished-at="2017-06-16T11:20:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123admin@]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUsernameAndPasswordUsingDataProvider -->
      </class> <!-- PajeObject.LoginCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
